import {
  Footer,
  Header,
  Hero,
  SupplierList,
  TopSuppliers,
} from "@/components/marketplace/Marketplace";
import {Metadata} from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function MarketplacePage() {
  return (
    <div>
      <Header />
      <Hero />
      <TopSuppliers />
      <SupplierList />
      <Footer />
    </div>
  );
}
